[project]
name = "auto-update"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "firerequests>=0.1.4",
    "patool>=4.0.1"
]
