name: Run main.py with uv

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true
          enable-cache: true
          cache-dependency-glob: |
            **/requirements*.txt
            **/pyproject.toml

      - run: |
          uv sync
          uv run main.py

