name: Run main.py with uv

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master]

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true
          enable-cache: true
          cache-dependency-glob: |
            **/requirements*.txt
            **/pyproject.toml

      - run: |
          uv sync
          uv run main.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push bin folder
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add bin/.gitkeep
          git commit -m "Add bin"
          git push origin master

          
      # - name: Create GitHub Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     tag_name: v1.0.0

      # - name: Upload bin.tar.gz
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     files: bin.tar.gz